name: flutter_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  get: 4.6.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
