// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKh5kAXuIozEqkYkVKB0fpa4ticf40mVU',
    appId: '1:47741691658:web:29f4ac1c81680474ddbcf3',
    messagingSenderId: '47741691658',
    projectId: 'msib-recipe-app',
    authDomain: 'msib-recipe-app.firebaseapp.com',
    storageBucket: 'msib-recipe-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ4Kc8Vy9mbBXDZ5rBYJxIMeU2FGK10GM',
    appId: '1:47741691658:android:337cdbf382bac6bfddbcf3',
    messagingSenderId: '47741691658',
    projectId: 'msib-recipe-app',
    storageBucket: 'msib-recipe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfRIu_XMgDtxdslA8HXL4DjAwSxq4cdjU',
    appId: '1:47741691658:ios:0644bb15b3f9ccb5ddbcf3',
    messagingSenderId: '47741691658',
    projectId: 'msib-recipe-app',
    storageBucket: 'msib-recipe-app.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfRIu_XMgDtxdslA8HXL4DjAwSxq4cdjU',
    appId: '1:47741691658:ios:0644bb15b3f9ccb5ddbcf3',
    messagingSenderId: '47741691658',
    projectId: 'msib-recipe-app',
    storageBucket: 'msib-recipe-app.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKh5kAXuIozEqkYkVKB0fpa4ticf40mVU',
    appId: '1:47741691658:web:af3cd85e6585e198ddbcf3',
    messagingSenderId: '47741691658',
    projectId: 'msib-recipe-app',
    authDomain: 'msib-recipe-app.firebaseapp.com',
    storageBucket: 'msib-recipe-app.appspot.com',
  );
}
